# Generated by Django 5.1.1 on 2025-07-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Основной заголовок объекта.', max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Уникальное название объекта.', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Основной заголовок объекта.', max_length=256, verbose_name='Заголовок'),
        ),
    ]
