# Generated by Django 5.1.1 on 2025-07-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_name_remove_location_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Географическое название.', max_length=256, verbose_name='Название места'),
        ),
    ]
